import {
  Loader2,
  Chrome,
  Mail,
  Lock,
  User,
  Calendar,
  MapPin,
  Clock,
  DollarSign,
  Users,
  Star,
  Heart,
  Share2,
  Download,
  Search,
  Filter,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Check,
  X,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  ChevronUp,
  MoreHorizontal,
  Settings,
  LogOut,
  Globe,
  Key,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  spinner: Loader2,
  google: Chrome,
  mail: Mail,
  lock: Lock,
  user: User,
  calendar: Calendar,
  mapPin: MapPin,
  globe: Globe,
  clock: Clock,
  dollarSign: DollarSign,
  users: Users,
  star: Star,
  heart: Heart,
  share: Share2,
  download: Download,
  search: Search,
  filter: Filter,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  eye: Eye,
  eyeOff: EyeOff,
  check: Check,
  x: X,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  moreHorizontal: MoreHorizontal,
  settings: Settings,
  logOut: LogOut,
  key: Key,
};
